title: Tom's personal page
description: Hi! Fancy seeing you here :o
url: "https://tombuster.github.io/"

header_pages:
  - index.md
  - about.md
  - gallery.md

listen_for_clients_preferred_style: true # false (default) or true

footer: 'follow me on <a href="https://twitter.com/TheTombuster">X</a>, <a href="https://www.instagram.com/the_tombuster/">Instagram</a> and on my <a href="https://www.youtube.com/channel/UCkVoYDqsETeRi4-klDgV6aQ">Youtube channel</a> where I upload whetever aligns with my interests!'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
